version: '3'
services:
  jenkins-proxy:
    build: ./jenkins-proxy
    restart: unless-stopped
    container_name: jenkins-proxy
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - JENKINS_DNS=${JENKINS_DNS}
    volumes:
      - ./jenkins-proxy/log:/var/log/nginx
  jenkins-server:
    build: ./jenkins-server
    restart: unless-stopped
    container_name: jenkins-server
    ports:
      - 127.0.0.1:8080:8080/tcp
      - 50000:50000/tcp
    volumes:
      - ./jenkins-server/home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
